package marshaller

const title = "2 Pakete SWIRL M 50 Micro Por - Staubsaugerbeutel"
const subtitle = "- ohne die Umkartons, daher günstigerer Versand möglich -"

const articleGeneralInfo = "Sie bieten auf 2 Packungen Staubsaugerbeutel ohne die Pappschachteln"
const articleDescription = "Hersteller: SWIRL / Melitta-Werke Minden\nTyp: M50 MicroPor Plus (schließt die Typen M 51 + M 53 ein)\n\nInhalt einer Packung: 4 Stück Staubfilterbeutel + 1 Filter\n\nSie erhalten somit zusammen 8 Beutel + 2 Filter\n\nBei den Beuteln handelt es sich um die moderneren Vliesbeutel mit mehrfach höherer Feinst-Staubfiltration und langanhaltend höherer Saugleistung für mehr Hygiene im Haushalt."
const articleShippingShort = "Versandkosten (sh. auch unten):\n1 Doppelpack: 0 Euro per Post – Brief (oder 2 Euro Aufpreis für DHL-Paketversand)\nab 2 Doppelpacks ( 4 Packungen ohne Umkartons): 0 Euro per DHL-Paket\n\nBriefversand erfolgt geschützt im Briefumschlag, ca. 5 cm dick, bitte 2-3 Tage Zustellzeit seitens der Post einkalkulieren."

const articleFitting = "Versandkosten (sh. auch unten):\n1 Doppelpack: 0 Euro per Post – Brief (oder 2 Euro Aufpreis für DHL-Paketversand)\nab 2 Doppelpacks ( 4 Packungen ohne Umkartons): 0 Euro per DHL-Paket\n\nBriefversand erfolgt geschützt im Briefumschlag, ca. 5 cm dick, bitte 2-3 Tage Zustellzeit seitens der Post einkalkulieren. --- to be continued"

const articleCondition = "Neuware, aus Lagerräumung. Die Auslieferung erfolgt ohne die Pappschachteln, die Beutel werden geschützt in Folienbeuteln ausgeliefert. Swirl Staubbeutel sind zuweilen nicht bedruckt, wir legen zur Orientierung die Shopping - Memos aus der Kartonverpackung der Lieferung bei."

const articleShipping = "Bitte holen Sie den gekauften Artikel innerhalb von einer Woche nach Auktionsende bei mir ab.\n\nWenn Sie Versand wünschen, dann betragen die Versandkosten innerhalb von Deutschland:\n\n1 Doppelpack (2 Packungen ohne Umkartons): 2,00 Euro per Post - Warensendung\nab 2 Doppelpacks (ab 4 Packungen ohne Umkartons): 4,00 Euro per DHL- Paket\n\nDie Übergabe Ihrer Bestellung an den Versanddienstleister erfolgt bei mir von Montag bis Freitag, einen Tag nach Zahlungseingang.\n\nLaufzeit von Post-Warensendungen: 7 Tage\nLaufzeit von Paketen: 2 Tage\n\nSollten Sie also schnelleren Versand wünschen, empfehle ich den Paketversand.\n\nDie Paketzustellung erfolgt innerhalb von 2 Tagen (Monat bis Freitag). Sie erhalten eine email mit einem Link zum Versanddienstleister zum Überprüfen des Versandstatus. Bei Postversand per Warensendung erhalten Sie eine email am Tag der Übergabe an die Post ohne Trackinglink.\nSollten Sie keine email von mir erhalten oder Fragen zum Versand Ihrer Sendung haben, setzen Sie sich bitte per email oder telefonisch mit mir in Verbindung."

const auction = "Die Zahlungsabwicklung erfolgt gem. §4 Abs. 2 der eBay-AGB. Gezahlt werden kann mit allen von eBay zur Verfügung gestellten Zahlungsmethoden über eBay, nicht jedoch mehr per Überweisung direkt an den Verkäufer."

const legal = "Die Vertragssprache ist deutsch.\nVertragsabschluß bei \"Sofort-Kaufen\"-Angeboten ab dem 12.03.2014:\nDer Vertragsabschluß richtet sich nach § 6 Nr. 4 der Allgemeinen Geschäftsbedingungen von eBay, die ich wie folgt zitiere:\n\"Bei Festpreisartikeln nimmt der Käufer das Angebot an, indem er den Button \"Sofort-Kaufen\" anklickt und anschließend bestätigt. Bei Festpreisartikeln, bei denen der Verkäufer die Option \"sofortige Bezahlung\" ausgewählt hat, nimmt der Käufer das Angebot an, indem er den Button \"Sofort-Kaufen\" anklickt und den unmittelbar nachfolgenden Zahlungsvorgang abschließt. Der Käufer kann Angebote für mehrere Artikel auch dadurch annehmen, dass er die Artikel in den Warenkorb (sofern verfügbar) legt und den unmittelbar nachfolgenden Zahlungsvorgang abschließt."

const seller = "Dipl.-Ing. (FH) - Dipl.-Wirt.-Ing.(FH)\nThomas Dellmann\nGroße Aue 6\n32361 Preußisch Oldendorf\n\nVollständiges Impressum, sh. unten.\n\nOnline-Streitbeilegung\nOnline-Streitbeilegung gemäß Art. 14 Abs. 1 ODR-VO: Die Europäische Kommission stellt eine Plattform zur Online-Streitbeilegung (OS) bereit, zu der Sie über den Punkt \"Impressum\" unten gelangen.\nZur Teilnahme an einem Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle sind wir nicht verpflichtet und nicht bereit."

const dsgvo = "Ich unterrichte Sie hierdurch gemäß Telemediengesetz und DSGVO, dass ich personenbezogene Daten durch elektronische Datenverarbeitung (EDV) in dem zum Zwecke der Begründung, inhaltlichen Ausgestaltung oder Änderung des Kaufvertrages (Kaufabwicklung) erhebe, verarbeite und nutze.\nDarüberhinaus gebe ich Ihre Daten nicht an Dritte weiter. Zur ausführlichen Information klicken Sie bitte unten auf das Feld 'Datenschutz' oder in das Feld zu den rechtlichen Informationen des Verkäufers in die Zeile 'Allgemeine Geschäftsbedingungen' zu diesem Angebot."
