openapi: 3.0.0
info:
  title: "Descriptinator Api"
  version: "1.0.0"
  contact:
    name: Tim Dellmann
    email: professional@email.com
    url: https://github.com/TiDe-bit/
tags:
  - name: Description
    description: Ebay article description 
paths:
  /:
    get:
      operationId: GetGenericDescription
      summary: GetGenericDescription
      tags: [ 'Metadata' ]
      responses:
        '200':
          description: OK
          schema:
            text/html
  /{articleNum}:
    get: 
      operationId: GetSpecificDescription
      summary: get specific description
      tags: [ 'Metadata' ]
      parameters: 
        - articleNum:
          type: string
      responses:
        '200':
          description: OK
          schema:
            text/html
  /edit/endpoint...: